openapi: 3.0.3
info:
    title: Tweets Service
    description: Service for managing tweets
    version: 0.0.1
servers:
    - url: http://0.0.0.0:80/api/posts
paths:
    /api/posts:
        delete:
            tags:
                - tweets
            summary: DeleteTweet tweets
            operationId: tweets#DeleteTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteTweetRequestBody'
                        example:
                            id: aefe166c-3559-11ef-b633-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: CreateTweet tweets
            operationId: tweets#CreateTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateTweetRequestBody'
                        example:
                            text: Quaerat odit.
                            user_id: aefdee08-3559-11ef-b633-b2d74bfa9f65
            responses:
                "200":
                    description: Created tweet
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Tweet'
                            example:
                                created_at: "2009-03-13T12:29:33Z"
                                id: aefdfb78-3559-11ef-b633-b2d74bfa9f65
                                text: Illo ut eaque quo modi ad.
                                user_id: aefdfc9a-3559-11ef-b633-b2d74bfa9f65
                "400":
                    description: 'BadRequest: Failed to create tweet'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: User was not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/posts/like:
        delete:
            tags:
                - tweets
            summary: DeleteTweetLike tweets
            operationId: tweets#DeleteTweetLike
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: aefe4038-3559-11ef-b633-b2d74bfa9f65
                            user_id: aefe41aa-3559-11ef-b633-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: LikeTweet tweets
            operationId: tweets#LikeTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: aefe2e2c-3559-11ef-b633-b2d74bfa9f65
                            user_id: aefe2f76-3559-11ef-b633-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/posts/reply:
        delete:
            tags:
                - tweets
            summary: DeleteReply tweets
            operationId: tweets#DeleteReply
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteTweetRequestBody'
                        example:
                            id: aefebd92-3559-11ef-b633-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: CreateReply tweets
            operationId: tweets#CreateReply
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateReplyRequestBody'
                        example:
                            text: Quo similique numquam laboriosam.
                            tweet_id: aefe9f92-3559-11ef-b633-b2d74bfa9f65
                            user_id: aefea0b4-3559-11ef-b633-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Reply'
                            example:
                                created_at: "1976-04-28T16:19:42Z"
                                id: aefeab36-3559-11ef-b633-b2d74bfa9f65
                                text: Similique eveniet et sint.
                                tweet_id: aefeac58-3559-11ef-b633-b2d74bfa9f65
                                user_id: aefead70-3559-11ef-b633-b2d74bfa9f65
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/posts/retweet:
        delete:
            tags:
                - tweets
            summary: DeleteRetweet tweets
            operationId: tweets#DeleteRetweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: aefe849e-3559-11ef-b633-b2d74bfa9f65
                            user_id: aefe8cc8-3559-11ef-b633-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: Retweet tweets
            operationId: tweets#Retweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: aefe52b2-3559-11ef-b633-b2d74bfa9f65
                            user_id: aefe53e8-3559-11ef-b633-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - tweets
            summary: Download ./gen/http/openapi.json
            operationId: tweets#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreateReplyRequestBody:
            type: object
            properties:
                text:
                    type: string
                    example: Omnis assumenda perferendis.
                tweet_id:
                    type: string
                    example: aeff62a6-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
                user_id:
                    type: string
                    example: aeff63a0-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
            example:
                text: Voluptatibus consequatur.
                tweet_id: aeff64a4-3559-11ef-b633-b2d74bfa9f65
                user_id: aeff65a8-3559-11ef-b633-b2d74bfa9f65
            required:
                - tweet_id
                - user_id
                - text
        CreateTweetRequestBody:
            type: object
            properties:
                text:
                    type: string
                    example: Reprehenderit aliquam.
                user_id:
                    type: string
                    example: aeff5220-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
            example:
                text: Qui saepe et voluptas dicta non.
                user_id: aeff5342-3559-11ef-b633-b2d74bfa9f65
            required:
                - user_id
                - text
        DeleteTweetRequestBody:
            type: object
            properties:
                id:
                    type: string
                    example: aeff5bbc-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
            example:
                id: aeff5cde-3559-11ef-b633-b2d74bfa9f65
            required:
                - id
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        LikeTweetRequestBody:
            type: object
            properties:
                tweet_id:
                    type: string
                    example: aeff5e1e-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
                user_id:
                    type: string
                    example: aeff5f2c-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
            example:
                tweet_id: aeff6026-3559-11ef-b633-b2d74bfa9f65
                user_id: aeff6120-3559-11ef-b633-b2d74bfa9f65
            required:
                - tweet_id
                - user_id
        Reply:
            type: object
            properties:
                created_at:
                    type: string
                    example: "2001-08-26T00:01:02Z"
                    format: date-time
                id:
                    type: string
                    example: aeff6706-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
                text:
                    type: string
                    example: Aut omnis voluptatem suscipit modi ut natus.
                tweet_id:
                    type: string
                    example: aeff6800-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
                user_id:
                    type: string
                    example: aeff68fa-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
            example:
                created_at: "1997-02-20T03:57:55Z"
                id: aeff6b20-3559-11ef-b633-b2d74bfa9f65
                text: Doloremque dolore ea error est omnis quibusdam.
                tweet_id: aeff6c10-3559-11ef-b633-b2d74bfa9f65
                user_id: aeff6d32-3559-11ef-b633-b2d74bfa9f65
            required:
                - id
                - tweet_id
                - user_id
                - text
                - created_at
        Tweet:
            type: object
            properties:
                created_at:
                    type: string
                    example: "1994-07-29T14:41:57Z"
                    format: date-time
                id:
                    type: string
                    example: aeff54aa-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
                text:
                    type: string
                    example: Provident sunt est temporibus consequatur consectetur libero.
                user_id:
                    type: string
                    example: aeff55ae-3559-11ef-b633-b2d74bfa9f65
                    format: uuid
            example:
                created_at: "2004-07-20T04:23:50Z"
                id: aeff581a-3559-11ef-b633-b2d74bfa9f65
                text: Et voluptatem aliquid eaque consequatur quibusdam qui.
                user_id: aeff591e-3559-11ef-b633-b2d74bfa9f65
            required:
                - id
                - user_id
                - text
                - created_at
tags:
    - name: tweets
      description: The tweets service performs operations on tweets information.
