swagger: "2.0"
info:
    title: Tweets Service
    description: Service for managing tweets
    version: 0.0.1
host: 0.0.0.0:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/tweets:
        post:
            tags:
                - tweets
            summary: CreateTweet tweets
            operationId: tweets#CreateTweet
            parameters:
                - name: CreateTweetRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsCreateTweetRequestBody'
                    required:
                        - user_id
                        - text
            responses:
                "200":
                    description: Created tweet
                    schema:
                        $ref: '#/definitions/TweetsCreateTweetResponseBody'
                        required:
                            - id
                            - user_id
                            - text
                            - created_at
                "400":
                    description: Failed to create tweet
                    schema:
                        $ref: '#/definitions/TweetsCreateTweetBadRequestResponseBody'
                "404":
                    description: User was not found
                    schema:
                        $ref: '#/definitions/TweetsCreateTweetNotFoundResponseBody'
            schemes:
                - http
        delete:
            tags:
                - tweets
            summary: DeleteTweet tweets
            operationId: tweets#DeleteTweet
            parameters:
                - name: DeleteTweetRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsDeleteTweetRequestBody'
                    required:
                        - id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TweetsDeleteTweetBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/TweetsDeleteTweetNotFoundResponseBody'
            schemes:
                - http
    /api/tweets/like:
        post:
            tags:
                - tweets
            summary: LikeTweet tweets
            operationId: tweets#LikeTweet
            parameters:
                - name: LikeTweetRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsLikeTweetRequestBody'
                    required:
                        - tweet_id
                        - user_id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TweetsLikeTweetBadRequestResponseBody'
            schemes:
                - http
        delete:
            tags:
                - tweets
            summary: DeleteTweetLike tweets
            operationId: tweets#DeleteTweetLike
            parameters:
                - name: DeleteTweetLikeRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsDeleteTweetLikeRequestBody'
                    required:
                        - tweet_id
                        - user_id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TweetsDeleteTweetLikeBadRequestResponseBody'
            schemes:
                - http
    /api/tweets/reply:
        post:
            tags:
                - tweets
            summary: CreateReply tweets
            operationId: tweets#CreateReply
            parameters:
                - name: CreateReplyRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsCreateReplyRequestBody'
                    required:
                        - tweet_id
                        - user_id
                        - text
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TweetsCreateReplyResponseBody'
                        required:
                            - id
                            - tweet_id
                            - user_id
                            - text
                            - created_at
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TweetsCreateReplyBadRequestResponseBody'
            schemes:
                - http
        delete:
            tags:
                - tweets
            summary: DeleteReply tweets
            operationId: tweets#DeleteReply
            parameters:
                - name: DeleteReplyRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsDeleteReplyRequestBody'
                    required:
                        - id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TweetsDeleteReplyBadRequestResponseBody'
            schemes:
                - http
    /api/tweets/retweet:
        post:
            tags:
                - tweets
            summary: Retweet tweets
            operationId: tweets#Retweet
            parameters:
                - name: RetweetRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsRetweetRequestBody'
                    required:
                        - tweet_id
                        - user_id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TweetsRetweetBadRequestResponseBody'
            schemes:
                - http
        delete:
            tags:
                - tweets
            summary: DeleteRetweet tweets
            operationId: tweets#DeleteRetweet
            parameters:
                - name: DeleteRetweetRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsDeleteRetweetRequestBody'
                    required:
                        - tweet_id
                        - user_id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TweetsDeleteRetweetBadRequestResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - tweets
            summary: Download ./gen/http/openapi.json
            operationId: tweets#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    TweetsCreateReplyBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: CreateReply_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsCreateReplyRequestBody:
        title: TweetsCreateReplyRequestBody
        type: object
        properties:
            text:
                type: string
                example: Et dolor.
            tweet_id:
                type: string
                example: db78a8f4-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
            user_id:
                type: string
                example: db78a9f8-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
        example:
            text: Illum aut et.
            tweet_id: db78ab56-2fed-11ef-b440-b2d74bfa9f65
            user_id: db78ac50-2fed-11ef-b440-b2d74bfa9f65
        required:
            - tweet_id
            - user_id
            - text
    TweetsCreateReplyResponseBody:
        title: TweetsCreateReplyResponseBody
        type: object
        properties:
            created_at:
                type: string
                example: "1995-03-05T00:45:05Z"
                format: date-time
            id:
                type: string
                example: Blanditiis qui et mollitia nisi.
            text:
                type: string
                example: Itaque qui magni explicabo et sed voluptate.
            tweet_id:
                type: string
                example: Ex minus.
            user_id:
                type: string
                example: Autem non error nam officia.
        example:
            created_at: "2013-08-17T11:26:33Z"
            id: Modi et dolore.
            text: Id ea molestiae neque.
            tweet_id: Et est.
            user_id: Nesciunt provident aut.
        required:
            - id
            - tweet_id
            - user_id
            - text
            - created_at
    TweetsCreateTweetBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: CreateTweet_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsCreateTweetNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CreateTweet_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsCreateTweetRequestBody:
        title: TweetsCreateTweetRequestBody
        type: object
        properties:
            text:
                type: string
                example: Assumenda fugiat.
            user_id:
                type: string
                example: db78890a-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
        example:
            text: Deleniti eum molestiae ipsam dignissimos.
            user_id: db788a36-2fed-11ef-b440-b2d74bfa9f65
        required:
            - user_id
            - text
    TweetsCreateTweetResponseBody:
        title: TweetsCreateTweetResponseBody
        type: object
        properties:
            created_at:
                type: string
                example: "1977-11-11T14:15:14Z"
                format: date-time
            id:
                type: string
                example: Assumenda repudiandae quasi.
            text:
                type: string
                example: Officiis sed consectetur sunt.
            user_id:
                type: string
                example: Sit repudiandae error sit quis tempore aperiam.
        example:
            created_at: "1970-09-01T15:36:06Z"
            id: Voluptas veniam.
            text: Consectetur necessitatibus autem.
            user_id: Repellat quas sint rerum dolores sint.
        required:
            - id
            - user_id
            - text
            - created_at
    TweetsDeleteReplyBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: DeleteReply_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsDeleteReplyRequestBody:
        title: TweetsDeleteReplyRequestBody
        type: object
        properties:
            id:
                type: string
                example: db78ae80-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
        example:
            id: db78af84-2fed-11ef-b440-b2d74bfa9f65
        required:
            - id
    TweetsDeleteRetweetBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: DeleteRetweet_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsDeleteRetweetRequestBody:
        title: TweetsDeleteRetweetRequestBody
        type: object
        properties:
            tweet_id:
                type: string
                example: db78a0a2-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
            user_id:
                type: string
                example: db78a1d8-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
        example:
            tweet_id: db78a2fa-2fed-11ef-b440-b2d74bfa9f65
            user_id: db78a3f4-2fed-11ef-b440-b2d74bfa9f65
        required:
            - tweet_id
            - user_id
    TweetsDeleteTweetBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: DeleteTweet_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsDeleteTweetLikeBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: DeleteTweetLike_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsDeleteTweetLikeRequestBody:
        title: TweetsDeleteTweetLikeRequestBody
        type: object
        properties:
            tweet_id:
                type: string
                example: db7895e4-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
            user_id:
                type: string
                example: db7896f2-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
        example:
            tweet_id: db789800-2fed-11ef-b440-b2d74bfa9f65
            user_id: db7898fa-2fed-11ef-b440-b2d74bfa9f65
        required:
            - tweet_id
            - user_id
    TweetsDeleteTweetNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: DeleteTweet_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsDeleteTweetRequestBody:
        title: TweetsDeleteTweetRequestBody
        type: object
        properties:
            id:
                type: string
                example: db788d42-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
        example:
            id: db788e6e-2fed-11ef-b440-b2d74bfa9f65
        required:
            - id
    TweetsLikeTweetBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: LikeTweet_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsLikeTweetRequestBody:
        title: TweetsLikeTweetRequestBody
        type: object
        properties:
            tweet_id:
                type: string
                example: db789080-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
            user_id:
                type: string
                example: db789198-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
        example:
            tweet_id: db78929c-2fed-11ef-b440-b2d74bfa9f65
            user_id: db7893a0-2fed-11ef-b440-b2d74bfa9f65
        required:
            - tweet_id
            - user_id
    TweetsRetweetBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Retweet_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsRetweetRequestBody:
        title: TweetsRetweetRequestBody
        type: object
        properties:
            tweet_id:
                type: string
                example: db789b2a-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
            user_id:
                type: string
                example: db789c2e-2fed-11ef-b440-b2d74bfa9f65
                format: uuid
        example:
            tweet_id: db789d46-2fed-11ef-b440-b2d74bfa9f65
            user_id: db789e68-2fed-11ef-b440-b2d74bfa9f65
        required:
            - tweet_id
            - user_id
