swagger: "2.0"
info:
    title: Profile Service
    description: Service for managing users' profile
    version: ""
host: 0.0.0.0:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/profile/{id}:
        get:
            tags:
                - profile
            summary: FindByID profile
            operationId: profile#FindByID
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ProfileFindByIDResponseBody'
                        required:
                            - username
                            - bio
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/ProfileFindByIDNotFoundResponseBody'
            schemes:
                - http
    /api/profile/{id}/edit/username:
        post:
            tags:
                - profile
            summary: UpdateUsername profile
            operationId: profile#UpdateUsername
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
                - name: UpdateUsernameRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfileUpdateUsernameRequestBody'
                    required:
                        - username
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProfileUpdateUsernameBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/ProfileUpdateUsernameNotFoundResponseBody'
            schemes:
                - http
    /api/profile/create:
        post:
            tags:
                - profile
            summary: CreateUser profile
            operationId: profile#CreateUser
            parameters:
                - name: CreateUserRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfileCreateUserRequestBody'
                    required:
                        - username
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ProfileCreateUserResponseBody'
                        required:
                            - username
                            - bio
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProfileCreateUserBadRequestResponseBody'
            schemes:
                - http
    /api/profile/delete:
        post:
            tags:
                - profile
            summary: DeleteUser profile
            operationId: profile#DeleteUser
            parameters:
                - name: DeleteUserRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfileDeleteUserRequestBody'
                    required:
                        - id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProfileDeleteUserBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/ProfileDeleteUserNotFoundResponseBody'
            schemes:
                - http
    /api/profile/edit/bio:
        post:
            tags:
                - profile
            summary: UpdateBio profile
            operationId: profile#UpdateBio
            parameters:
                - name: UpdateBioRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfileUpdateBioRequestBody'
                    required:
                        - id
                        - bio
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProfileUpdateBioBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/ProfileUpdateBioNotFoundResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - profile
            summary: Download ./gen/http/openapi.json
            operationId: profile#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    ProfileCreateUserBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: CreateUser_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileCreateUserRequestBody:
        title: ProfileCreateUserRequestBody
        type: object
        properties:
            username:
                type: string
                example: Voluptatem omnis in.
        example:
            username: Exercitationem ut molestiae laudantium velit incidunt nisi.
        required:
            - username
    ProfileCreateUserResponseBody:
        title: ProfileCreateUserResponseBody
        type: object
        properties:
            bio:
                type: string
                example: Minima exercitationem asperiores officiis corrupti voluptatem qui.
            username:
                type: string
                example: Ut esse dolor.
        example:
            bio: Occaecati nihil quae pariatur qui omnis possimus.
            username: Perspiciatis velit.
        required:
            - username
            - bio
    ProfileDeleteUserBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: DeleteUser_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileDeleteUserNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: DeleteUser_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileDeleteUserRequestBody:
        title: ProfileDeleteUserRequestBody
        type: object
        properties:
            id:
                type: integer
                example: 3398060815818463807
                format: int64
        example:
            id: 2709295796060797314
        required:
            - id
    ProfileFindByIDNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: FindByID_NotFound_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileFindByIDResponseBody:
        title: ProfileFindByIDResponseBody
        type: object
        properties:
            bio:
                type: string
                example: Modi alias perferendis aperiam architecto.
            username:
                type: string
                example: Sapiente qui distinctio et atque.
        example:
            bio: Provident sed iure vel eveniet ea qui.
            username: Optio sit rerum.
        required:
            - username
            - bio
    ProfileUpdateBioBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: UpdateBio_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileUpdateBioNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: UpdateBio_NotFound_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileUpdateBioRequestBody:
        title: ProfileUpdateBioRequestBody
        type: object
        properties:
            bio:
                type: string
                example: Accusamus ut ut est voluptatem commodi.
            id:
                type: integer
                example: 5199263535650841009
                format: int64
        example:
            bio: Qui accusantium voluptas non qui consequatur fuga.
            id: 2161839234274357760
        required:
            - id
            - bio
    ProfileUpdateUsernameBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: UpdateUsername_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileUpdateUsernameNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: UpdateUsername_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileUpdateUsernameRequestBody:
        title: ProfileUpdateUsernameRequestBody
        type: object
        properties:
            username:
                type: string
                example: Et ullam.
        example:
            username: Recusandae ipsam eaque veniam est provident.
        required:
            - username
