openapi: 3.0.3
info:
    title: Users Service
    description: Service for managing users
    version: "1.0"
servers:
    - url: http://0.0.0.0:80/api/users
paths:
    /api/users:
        delete:
            tags:
                - users
            summary: DeleteUser users
            operationId: users#DeleteUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteUserRequestBody'
                        example:
                            id: Minima quis incidunt saepe est.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - users
            summary: CreateUser users
            operationId: users#CreateUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateUserRequestBody'
                        example:
                            display_name: Officia expedita consequuntur.
                            username: Minus eaque tempora in laborum.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                            example:
                                bio: Dignissimos blanditiis nihil ipsum error nostrum.
                                created_at: "1977-02-10T22:09:42Z"
                                display_name: Quo nihil ut veniam mollitia numquam quo.
                                id: 5c57e54c-1e65-11ef-8ef1-0242ac120003
                                updated_at: "2008-12-06T15:49:22Z"
                                username: Ab recusandae.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/{id}:
        get:
            tags:
                - users
            summary: FindUserByID users
            operationId: users#FindUserByID
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Consequatur ut optio nisi.
                  example: Vel nobis.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                            example:
                                bio: Illum aut id.
                                created_at: "1992-08-31T01:16:09Z"
                                display_name: Repellendus dolores vel doloribus nihil et.
                                id: 5c580575-1e65-11ef-8ef1-0242ac120003
                                updated_at: "1984-03-14T07:00:57Z"
                                username: Possimus tempore dicta aut dicta eum dolorum.
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/{id}/bio:
        post:
            tags:
                - users
            summary: UpdateBio users
            operationId: users#UpdateBio
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Quo quia ipsa nostrum.
                  example: Dicta quisquam eos voluptate ducimus.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateBioRequestBody'
                        example:
                            bio: Non facilis et fugit.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/{id}/followers:
        get:
            tags:
                - users
            summary: GetFollowers users
            operationId: users#GetFollowers
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Quia sapiente ipsa.
                  example: Officiis rerum similique veritatis culpa.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/User'
                                example:
                                    - bio: Magni nobis repellendus ut suscipit suscipit.
                                      created_at: "1989-12-28T14:47:07Z"
                                      display_name: Rerum ducimus sed quia optio eligendi quo.
                                      id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                      updated_at: "1999-10-21T07:37:18Z"
                                      username: Inventore in.
                                    - bio: Magni nobis repellendus ut suscipit suscipit.
                                      created_at: "1989-12-28T14:47:07Z"
                                      display_name: Rerum ducimus sed quia optio eligendi quo.
                                      id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                      updated_at: "1999-10-21T07:37:18Z"
                                      username: Inventore in.
                                    - bio: Magni nobis repellendus ut suscipit suscipit.
                                      created_at: "1989-12-28T14:47:07Z"
                                      display_name: Rerum ducimus sed quia optio eligendi quo.
                                      id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                      updated_at: "1999-10-21T07:37:18Z"
                                      username: Inventore in.
                            example:
                                - bio: Magni nobis repellendus ut suscipit suscipit.
                                  created_at: "1989-12-28T14:47:07Z"
                                  display_name: Rerum ducimus sed quia optio eligendi quo.
                                  id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                  updated_at: "1999-10-21T07:37:18Z"
                                  username: Inventore in.
                                - bio: Magni nobis repellendus ut suscipit suscipit.
                                  created_at: "1989-12-28T14:47:07Z"
                                  display_name: Rerum ducimus sed quia optio eligendi quo.
                                  id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                  updated_at: "1999-10-21T07:37:18Z"
                                  username: Inventore in.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/{id}/followings:
        get:
            tags:
                - users
            summary: GetFollowings users
            operationId: users#GetFollowings
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Molestiae magni natus et architecto possimus soluta.
                  example: Ut cum facere sed ea.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/User'
                                example:
                                    - bio: Magni nobis repellendus ut suscipit suscipit.
                                      created_at: "1989-12-28T14:47:07Z"
                                      display_name: Rerum ducimus sed quia optio eligendi quo.
                                      id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                      updated_at: "1999-10-21T07:37:18Z"
                                      username: Inventore in.
                                    - bio: Magni nobis repellendus ut suscipit suscipit.
                                      created_at: "1989-12-28T14:47:07Z"
                                      display_name: Rerum ducimus sed quia optio eligendi quo.
                                      id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                      updated_at: "1999-10-21T07:37:18Z"
                                      username: Inventore in.
                                    - bio: Magni nobis repellendus ut suscipit suscipit.
                                      created_at: "1989-12-28T14:47:07Z"
                                      display_name: Rerum ducimus sed quia optio eligendi quo.
                                      id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                      updated_at: "1999-10-21T07:37:18Z"
                                      username: Inventore in.
                                    - bio: Magni nobis repellendus ut suscipit suscipit.
                                      created_at: "1989-12-28T14:47:07Z"
                                      display_name: Rerum ducimus sed quia optio eligendi quo.
                                      id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                      updated_at: "1999-10-21T07:37:18Z"
                                      username: Inventore in.
                            example:
                                - bio: Magni nobis repellendus ut suscipit suscipit.
                                  created_at: "1989-12-28T14:47:07Z"
                                  display_name: Rerum ducimus sed quia optio eligendi quo.
                                  id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                  updated_at: "1999-10-21T07:37:18Z"
                                  username: Inventore in.
                                - bio: Magni nobis repellendus ut suscipit suscipit.
                                  created_at: "1989-12-28T14:47:07Z"
                                  display_name: Rerum ducimus sed quia optio eligendi quo.
                                  id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                  updated_at: "1999-10-21T07:37:18Z"
                                  username: Inventore in.
                                - bio: Magni nobis repellendus ut suscipit suscipit.
                                  created_at: "1989-12-28T14:47:07Z"
                                  display_name: Rerum ducimus sed quia optio eligendi quo.
                                  id: 5c58709e-1e65-11ef-8ef1-0242ac120003
                                  updated_at: "1999-10-21T07:37:18Z"
                                  username: Inventore in.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/{id}/username:
        post:
            tags:
                - users
            summary: UpdateUsername users
            operationId: users#UpdateUsername
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Temporibus itaque.
                  example: Cum enim eum molestiae.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateUsernameRequestBody'
                        example:
                            username: Soluta itaque eaque voluptatum est consequatur.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/block:
        delete:
            tags:
                - users
            summary: Unblock users
            operationId: users#Unblock
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BlockRequestBody'
                        example:
                            blocked_user_id: Est quis qui.
                            blocking_user_id: Sapiente corporis a esse et.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - users
            summary: Block users
            operationId: users#Block
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BlockRequestBody'
                        example:
                            blocked_user_id: Voluptatum quo enim eos ex laborum.
                            blocking_user_id: Sit perferendis et.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/follow:
        delete:
            tags:
                - users
            summary: Unfollow users
            operationId: users#Unfollow
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowRequestBody'
                        example:
                            followee_id: Aut dignissimos.
                            follower_id: Voluptas enim dolor dolore dicta.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - users
            summary: Follow users
            operationId: users#Follow
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowRequestBody'
                        example:
                            followee_id: Aut inventore ut est et.
                            follower_id: Distinctio dolores aut fugit.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/mute:
        delete:
            tags:
                - users
            summary: Unmute users
            operationId: users#Unmute
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/MuteRequestBody'
                        example:
                            muted_user_id: Voluptatem porro tempora quis laborum impedit iusto.
                            muting_user_id: Vero sit explicabo.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - users
            summary: Mute users
            operationId: users#Mute
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/MuteRequestBody'
                        example:
                            muted_user_id: Odio fuga corporis commodi.
                            muting_user_id: In quibusdam dignissimos ullam.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - users
            summary: Download ./gen/http/openapi.json
            operationId: users#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        BlockRequestBody:
            type: object
            properties:
                blocked_user_id:
                    type: string
                    example: Praesentium autem dolore quisquam velit.
                blocking_user_id:
                    type: string
                    example: Consequuntur aut et.
            example:
                blocked_user_id: Illum exercitationem maxime dolores.
                blocking_user_id: Quasi laborum laboriosam harum et voluptatem voluptas.
            required:
                - blocked_user_id
                - blocking_user_id
        CreateUserRequestBody:
            type: object
            properties:
                display_name:
                    type: string
                    example: Debitis similique rerum ea voluptates.
                username:
                    type: string
                    example: Distinctio nihil dolor dolor inventore dolorum.
            example:
                display_name: Est delectus aut maxime placeat id numquam.
                username: Veniam magni voluptas aut error.
            required:
                - username
                - display_name
        DeleteUserRequestBody:
            type: object
            properties:
                id:
                    type: string
                    example: Explicabo possimus quia.
            example:
                id: Quis possimus dolores quas commodi sit.
            required:
                - id
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        FollowRequestBody:
            type: object
            properties:
                followee_id:
                    type: string
                    example: Assumenda vel sit ducimus.
                follower_id:
                    type: string
                    example: Et nobis et eos iure vel.
            example:
                followee_id: Dolorum distinctio.
                follower_id: Dolorem est rerum nam voluptatem similique omnis.
            required:
                - follower_id
                - followee_id
        MuteRequestBody:
            type: object
            properties:
                muted_user_id:
                    type: string
                    example: Consectetur quidem occaecati reiciendis repellendus.
                muting_user_id:
                    type: string
                    example: Sit sed sit deserunt rerum.
            example:
                muted_user_id: Exercitationem cupiditate dolorem pariatur similique nostrum vel.
                muting_user_id: Molestiae voluptas.
            required:
                - muted_user_id
                - muting_user_id
        UpdateBioRequestBody:
            type: object
            properties:
                bio:
                    type: string
                    example: Illum praesentium.
            example:
                bio: Quae cupiditate.
            required:
                - bio
        UpdateUsernameRequestBody:
            type: object
            properties:
                username:
                    type: string
                    example: Quam aut.
            example:
                username: Harum dicta.
            required:
                - username
        User:
            type: object
            properties:
                bio:
                    type: string
                    example: Non consequuntur sed explicabo aut ad natus.
                created_at:
                    type: string
                    example: "2014-11-14T07:14:09Z"
                    format: date-time
                display_name:
                    type: string
                    example: Quis sint maxime ratione voluptatum.
                id:
                    type: string
                    example: 5c5903a8-1e65-11ef-8ef1-0242ac120003
                    format: uuid
                updated_at:
                    type: string
                    example: "1992-07-22T12:16:41Z"
                    format: date-time
                username:
                    type: string
                    example: Est eius fugit voluptatem.
            example:
                bio: Neque est eos quos officiis est eum.
                created_at: "2008-11-11T06:49:33Z"
                display_name: Et est consequatur repellat reiciendis magni.
                id: 5c5905f7-1e65-11ef-8ef1-0242ac120003
                updated_at: "1980-02-21T16:28:08Z"
                username: Similique incidunt.
            required:
                - id
                - username
                - display_name
                - bio
                - created_at
                - updated_at
tags:
    - name: users
      description: The users service performs operations on users information.
