swagger: "2.0"
info:
    title: Users Service
    description: Service for managing users
    version: ""
host: 0.0.0.0:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/users:
        post:
            tags:
                - users
            summary: CreateUser users
            operationId: users#CreateUser
            parameters:
                - name: CreateUserRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UsersCreateUserRequestBody'
                    required:
                        - username
                        - display_name
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UsersCreateUserResponseBody'
                        required:
                            - id
                            - username
                            - display_name
                            - bio
                            - created_at
                            - updated_at
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UsersCreateUserBadRequestResponseBody'
            schemes:
                - http
        delete:
            tags:
                - users
            summary: DeleteUser users
            operationId: users#DeleteUser
            parameters:
                - name: DeleteUserRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UsersDeleteUserRequestBody'
                    required:
                        - id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UsersDeleteUserBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/UsersDeleteUserNotFoundResponseBody'
            schemes:
                - http
    /api/users/{id}:
        get:
            tags:
                - users
            summary: FindUserByID users
            operationId: users#FindUserByID
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UsersFindUserByIDResponseBody'
                        required:
                            - id
                            - username
                            - display_name
                            - bio
                            - created_at
                            - updated_at
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/UsersFindUserByIDNotFoundResponseBody'
            schemes:
                - http
    /api/users/{id}/bio:
        post:
            tags:
                - users
            summary: UpdateBio users
            operationId: users#UpdateBio
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                - name: UpdateBioRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UsersUpdateBioRequestBody'
                    required:
                        - bio
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UsersUpdateBioBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/UsersUpdateBioNotFoundResponseBody'
            schemes:
                - http
    /api/users/{id}/followers:
        get:
            tags:
                - users
            summary: GetFollowers users
            operationId: users#GetFollowers
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/UserResponse'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UsersGetFollowersBadRequestResponseBody'
            schemes:
                - http
    /api/users/{id}/followings:
        get:
            tags:
                - users
            summary: GetFollowings users
            operationId: users#GetFollowings
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/UserResponse'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UsersGetFollowingsBadRequestResponseBody'
            schemes:
                - http
    /api/users/{id}/username:
        post:
            tags:
                - users
            summary: UpdateUsername users
            operationId: users#UpdateUsername
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                - name: UpdateUsernameRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UsersUpdateUsernameRequestBody'
                    required:
                        - username
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UsersUpdateUsernameBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/UsersUpdateUsernameNotFoundResponseBody'
            schemes:
                - http
    /api/users/follow:
        post:
            tags:
                - users
            summary: Follow users
            operationId: users#Follow
            parameters:
                - name: FollowRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UsersFollowRequestBody'
                    required:
                        - follower_id
                        - followee_id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UsersFollowBadRequestResponseBody'
            schemes:
                - http
        delete:
            tags:
                - users
            summary: Unfollow users
            operationId: users#Unfollow
            parameters:
                - name: UnfollowRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UsersUnfollowRequestBody'
                    required:
                        - follower_id
                        - followee_id
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UsersUnfollowBadRequestResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - users
            summary: Download ./gen/http/openapi.json
            operationId: users#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    UserResponse:
        title: UserResponse
        type: object
        properties:
            bio:
                type: string
                example: Quasi dolorem enim magni voluptatem.
            created_at:
                type: string
                example: "1982-04-20T16:08:09Z"
                format: date-time
            display_name:
                type: string
                example: Aspernatur qui.
            id:
                type: string
                example: 8b514d19-0c6f-11ef-b1fe-0242ac120003
                format: uuid
            updated_at:
                type: string
                example: "1984-02-04T06:21:18Z"
                format: date-time
            username:
                type: string
                example: Ratione doloribus voluptatibus autem natus.
        example:
            bio: Pariatur esse et officia dignissimos ipsum perferendis.
            created_at: "2006-11-30T08:24:44Z"
            display_name: Unde quas veniam quod dolor enim ullam.
            id: 8b514fb3-0c6f-11ef-b1fe-0242ac120003
            updated_at: "1974-12-18T20:14:58Z"
            username: Delectus quia perferendis ut cupiditate.
        required:
            - id
            - username
            - display_name
            - bio
            - created_at
            - updated_at
    UsersCreateUserBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: CreateUser_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersCreateUserRequestBody:
        title: UsersCreateUserRequestBody
        type: object
        properties:
            display_name:
                type: string
                example: Est doloremque fugit nisi beatae assumenda vel.
            username:
                type: string
                example: Consequuntur vero esse esse cupiditate qui ipsam.
        example:
            display_name: Eum est aut magni porro eveniet.
            username: Architecto ducimus.
        required:
            - username
            - display_name
    UsersCreateUserResponseBody:
        title: UsersCreateUserResponseBody
        type: object
        properties:
            bio:
                type: string
                example: Commodi ullam in quibusdam dignissimos.
            created_at:
                type: string
                example: "2004-09-28T08:56:04Z"
                format: date-time
            display_name:
                type: string
                example: Aut ut eum odio fuga.
            id:
                type: string
                example: 8b513a85-0c6f-11ef-b1fe-0242ac120003
                format: uuid
            updated_at:
                type: string
                example: "1988-12-24T20:27:22Z"
                format: date-time
            username:
                type: string
                example: Quo earum odit expedita.
        example:
            bio: Omnis voluptates nulla earum dolor in ducimus.
            created_at: "2001-12-14T01:19:27Z"
            display_name: Ut et explicabo pariatur et magni ea.
            id: 8b513d6c-0c6f-11ef-b1fe-0242ac120003
            updated_at: "1985-01-03T18:06:08Z"
            username: Voluptas et.
        required:
            - id
            - username
            - display_name
            - bio
            - created_at
            - updated_at
    UsersDeleteUserBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: DeleteUser_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersDeleteUserNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: DeleteUser_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersDeleteUserRequestBody:
        title: UsersDeleteUserRequestBody
        type: object
        properties:
            id:
                type: string
                example: Expedita temporibus quis in explicabo.
        example:
            id: Distinctio vel harum omnis necessitatibus temporibus.
        required:
            - id
    UsersFindUserByIDNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: FindUserByID_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersFindUserByIDResponseBody:
        title: UsersFindUserByIDResponseBody
        type: object
        properties:
            bio:
                type: string
                example: Aut rem est voluptatem tempora sed.
            created_at:
                type: string
                example: "2015-03-01T00:06:59Z"
                format: date-time
            display_name:
                type: string
                example: Et architecto odit repellendus deserunt laborum.
            id:
                type: string
                example: 8b5142b8-0c6f-11ef-b1fe-0242ac120003
                format: uuid
            updated_at:
                type: string
                example: "2015-02-05T08:44:04Z"
                format: date-time
            username:
                type: string
                example: Quod aut.
        example:
            bio: Aut repellat voluptatibus et.
            created_at: "1980-03-17T18:49:27Z"
            display_name: Explicabo molestias molestias.
            id: 8b514567-0c6f-11ef-b1fe-0242ac120003
            updated_at: "1970-03-09T06:20:25Z"
            username: Culpa repellendus.
        required:
            - id
            - username
            - display_name
            - bio
            - created_at
            - updated_at
    UsersFollowBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Follow_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersFollowRequestBody:
        title: UsersFollowRequestBody
        type: object
        properties:
            followee_id:
                type: string
                example: Consequatur est.
            follower_id:
                type: string
                example: Qui occaecati.
        example:
            followee_id: Nesciunt dolores in voluptas perferendis iusto.
            follower_id: In tempore iste labore.
        required:
            - follower_id
            - followee_id
    UsersGetFollowersBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: GetFollowers_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersGetFollowingsBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: GetFollowings_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersUnfollowBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Unfollow_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersUnfollowRequestBody:
        title: UsersUnfollowRequestBody
        type: object
        properties:
            followee_id:
                type: string
                example: Accusamus et repudiandae modi.
            follower_id:
                type: string
                example: Sit beatae cum iusto voluptatibus.
        example:
            followee_id: Quo animi itaque dicta.
            follower_id: Ad molestias fugit quod nemo illo officia.
        required:
            - follower_id
            - followee_id
    UsersUpdateBioBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: UpdateBio_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersUpdateBioNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: UpdateBio_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersUpdateBioRequestBody:
        title: UsersUpdateBioRequestBody
        type: object
        properties:
            bio:
                type: string
                example: Ullam animi et vitae autem similique.
        example:
            bio: Veniam quos debitis et.
        required:
            - bio
    UsersUpdateUsernameBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: UpdateUsername_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersUpdateUsernameNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: UpdateUsername_NotFound_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UsersUpdateUsernameRequestBody:
        title: UsersUpdateUsernameRequestBody
        type: object
        properties:
            username:
                type: string
                example: Ea laboriosam non sapiente incidunt.
        example:
            username: Praesentium sed vel occaecati laudantium modi aliquam.
        required:
            - username
